# Configuração de fallback para eliminar placeholders
# Este arquivo fornece valores padrão seguros quando os segredos do Azure Key Vault não estão disponíveis

spring:
  # Database Configuration - Fallbacks seguros
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/db_autenticacao}
    username: ${SPRING_R2DBC_USERNAME:autenticacao_user}
    password: ${SPRING_R2DBC_PASSWORD:changeme}

  flyway:
    url: ${SPRING_FLYWAY_URL:jdbc:mysql://localhost:3306/db_autenticacao}
    user: ${SPRING_FLYWAY_USER:autenticacao_user}
    password: ${SPRING_FLYWAY_PASSWORD:changeme}

  # Redis Configuration - Fallbacks seguros
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      database: ${SPRING_DATA_REDIS_DATABASE:1}

  # Azure Configuration - Fallbacks seguros
  cloud:
    azure:
      keyvault:
        secret:
          enabled: ${AZURE_KEYVAULT_ENABLED:false}
          endpoint: ${AZURE_KEYVAULT_ENDPOINT:}
        credential:
          tenant-id: ${AZURE_TENANT_ID:}
          subscription-id: ${AZURE_SUBSCRIPTION_ID:}
          client-id: ${AZURE_CLIENT_ID:}

# Server Configuration - Fallback seguro
server:
  port: ${SERVER_PORT:8081}
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEYSTORE_PATH:}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:}

# JWT Configuration - Fallbacks seguros
jwt:
  # Configurações básicas
  issuer: ${JWT_ISSUER:https://conexaodesorte.com.br}
  audience: ${JWT_AUDIENCE:conexao-de-sorte-frontend-app}
  algorithm: ${JWT_ALGORITHM:RS256}

  # Validade dos tokens
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:86400}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:604800}

  # Chaves (via secrets ou fallback vazio)
  signing-key: ${JWT_SIGNING_KEY:}
  verification-key: ${JWT_VERIFICATION_KEY:}
  key-id: ${JWT_KEY_ID:}
  secret: ${JWT_SECRET:}

  # Azure Key Vault keys
  key-vault:
    enabled: ${JWT_KEYVAULT_ENABLED:false}
    private-key-name: ${JWT_PRIVATE_KEY_NAME:jwt-private-key}
    public-key-name: ${JWT_PUBLIC_KEY_NAME:jwt-public-key}
    key-id-name: ${JWT_KEY_ID_NAME:jwt-key-id}
    secret-name: ${JWT_SECRET_NAME:jwt-secret}

  # JWKS cache
  jwks-cache-duration: ${JWT_JWKS_CACHE_DURATION:PT1H}

  # Rotação
  rotation:
    enabled: ${JWT_ROTATION_ENABLED:false}
    schedule: ${JWT_ROTATION_SCHEDULE:0 0 2 * * ?}

# CORS Configuration - Fallbacks seguros
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://conexaodesorte.com.br}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:false}
  max-age: 3600

# Encryption Configuration - Fallbacks seguros
encryption:
  master-key: ${ENCRYPTION_MASTER_KEY:}
  backup-key: ${ENCRYPTION_BACKUP_KEY:}
  algorithm: AES-256-GCM
  key-derivation: PBKDF2WithHmacSHA256
  iterations: 100000

# Feature Flags - Fallbacks seguros
feature:
  auth-microservice: ${FEATURE_AUTH_MICROSERVICE:true}
  jwks-rotation: ${FEATURE_JWKS_ROTATION:false}
  audit-logging: ${FEATURE_AUDIT_LOGGING:true}
  metrics-collection: ${FEATURE_METRICS_COLLECTION:true}

# Rate Limiting Configuration - Fallbacks seguros
rate-limit:
  enabled: true
  default-requests-per-minute: 60
  endpoints:
    "/auth/token":
      requests-per-minute: ${RATE_LIMIT_LOGIN:10}
      burst-capacity: ${RATE_LIMIT_LOGIN_BURST:20}
    "/auth/refresh":
      requests-per-minute: ${RATE_LIMIT_VALIDATION:100}
      burst-capacity: ${RATE_LIMIT_VALIDATION_BURST:200}

# Logging Configuration - Fallbacks seguros
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    "[br.tec.facilitaservicos.autenticacao]": ${LOG_LEVEL_AUTENTICACAO:INFO}
    "[org.springframework.security]": ${LOG_LEVEL_SECURITY:WARN}
    "[org.springframework.r2dbc]": ${LOG_LEVEL_R2DBC:WARN}
    "[io.r2dbc.mysql]": ${LOG_LEVEL_MYSQL:WARN}
    "[com.azure]": ${LOG_LEVEL_AZURE:WARN}

  file:
    name: ${LOG_FILE:/var/log/autenticacao/application.log}

# Tracing Configuration - Fallback seguro
management:
  tracing:
    sampling:
      probability: ${TRACING_PROBABILITY:0.0}

# Azure Key Vault Configuration - Fallback seguro
azure:
  keyvault:
    enabled: ${AZURE_KEYVAULT_ENABLED:false}
    endpoint: ${AZURE_KEYVAULT_ENDPOINT:}
    client-id: ${AZURE_CLIENT_ID:}
    tenant-id: ${AZURE_TENANT_ID:}
