spring:
  jackson:
    time-zone: America/Sao_Paulo
    locale: pt_BR
  application:
    name: autenticacao
    
  profiles:
    default: prod
    active: prod
    # Profiles são sobrescritos via SPRING_PROFILES_ACTIVE no deployment
  
  main:
    allow-bean-definition-overriding: true
    
  # Cache reativo (Redis) - Configuração crítica para autenticação
  data:
    redis:
      host: ${conexao-de-sorte-redis-host}
      port: ${conexao-de-sorte-redis-port}
      password: ${conexao-de-sorte-redis-password}
      database: ${conexao-de-sorte-redis-database}
      timeout: 3000ms
      connect-timeout: 10000ms
      lettuce:
        pool:
          enabled: true
          max-active: 30
          max-idle: 15
          min-idle: 8
          max-wait: 5000ms
          time-between-eviction-runs: 30s
        cluster:
          refresh:
            adaptive: true
            period: 60s

  # Cache Configuration - Segurança crítica
  cache:
    type: redis
    cache-names: rsa-private-key, rsa-public-key, key-id, valid-tokens, jwks
    redis:
      time-to-live: PT30M # TTL padrão para segurança
      cache-null-values: false
      key-prefix: "auth:"
      use-key-prefix: true
          
  # Azure Key Vault with manual configuration
  cloud:
    azure:
      keyvault:
        secret:
          enabled: ${AZURE_KEYVAULT_ENABLED}
          endpoint: ${AZURE_KEYVAULT_ENDPOINT}
      profile:
        tenant-id: ${AZURE_TENANT_ID}
        subscription-id: ${AZURE_SUBSCRIPTION_ID}
        client-id: ${AZURE_CLIENT_ID}
  
  # Configtree secret management
  config:
    import:
      - optional:configtree:/etc/secrets/azure/
      - optional:configtree:/mnt/secrets/
      - optional:file:./secrets.properties
      
  r2dbc:
    # Configuração segura - apenas Azure Key Vault, sem fallbacks
    url: ${conexao-de-sorte-database-r2dbc-url}
    username: ${conexao-de-sorte-database-username}
    password: ${conexao-de-sorte-database-password}
    pool:
      initial-size: 1  # Reduzido para startup mais rápido
      max-size: 10     # Reduzido para startup mais rápido
      max-idle-time: 10m
      max-acquire-time: 15s    # Reduzido para evitar travamentos
      max-create-connection-time: 10s  # Reduzido para evitar travamentos
      max-life-time: 30m
      validation-query: SELECT 1

  flyway:
    enabled: true
    # Configuração segura - apenas Azure Key Vault, sem fallbacks
    url: ${conexao-de-sorte-database-jdbc-url}
    user: ${conexao-de-sorte-database-username}
    password: ${conexao-de-sorte-database-password}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false

user-service:
  url: ${USER_SERVICE_URL}

# Server Configuration (aplicável a todos os perfis)
server:
  port: ${conexao-de-sorte-server-port}
  shutdown: graceful
  
  # SSL/TLS Configuration
  ssl:
    enabled: false  # TLS termina no Traefik (ACME) - forçar false
    key-store: ${conexao-de-sorte-ssl-keystore-path}
    key-store-password: ${conexao-de-sorte-ssl-keystore-password}
    key-store-type: PKCS12
    
  netty:
    connection-timeout: 20s
    h2c-max-content-length: 0B
    
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

# Management and Health Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
      cors:
        allowed-origins: "*"
        allowed-methods: GET
        
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
        
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
      
  metrics:
    distribution:
      percentiles:
        "[http.server.requests]": 0.5,0.95,0.99
            
  prometheus:
    metrics:
      export:
        enabled: true
        step: 60s
            
  tracing:
    enabled: true
    sampling:
      probability: ${TRACING_PROBABILITY}

# Custom Application Properties
app:
  # JWT Configuration with secure secret management
  jwt:
    # Duracao dos tokens (em segundos)
    access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}  # Configurado via Key Vault
    refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}  # Configurado via Key Vault
    
    # Azure Key Vault keys - using secure naming
    key-vault:
      enabled: ${JWT_KEYVAULT_ENABLED}
      private-key-name: ${JWT_PRIVATE_KEY_NAME}
      public-key-name: ${JWT_PUBLIC_KEY_NAME}
      key-id-name: ${JWT_KEY_ID_NAME}
      secret-name: ${JWT_SECRET_NAME}
      
    # Configuração segura - apenas Azure Key Vault, sem fallbacks
    # Removido fallback inseguro para forçar uso exclusivo do Key Vault
      
    # Issuer e Audience
    issuer: ${conexao-de-sorte-jwt-issuer}
    audience: ${JWT_AUDIENCE}
    
    # JWKS cache
    jwks-cache-duration: ${JWT_JWKS_CACHE_DURATION}  # Configurado via Key Vault
    
    # Security settings
    algorithm: ${JWT_ALGORITHM}
    rotation:
      enabled: ${JWT_ROTATION_ENABLED}
      schedule: ${JWT_ROTATION_SCHEDULE}  # Configurado via Key Vault

  # CORS Configuration
  cors:
    allowed-origins: ${conexao-de-sorte-cors-allowed-origins}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: ${conexao-de-sorte-cors-allow-credentials}
    max-age: 3600

  # Rate Limiting
  rate-limit:
    enabled: true
    default-requests-per-minute: 60
    endpoints:
      "/auth/token":
        requests-per-minute: 10
        burst-capacity: 20
      "/auth/refresh":
        requests-per-minute: 30
        burst-capacity: 50
      "/auth/introspect":
        requests-per-minute: 100
        burst-capacity: 200

  # Security Headers
  security:
    headers:
      content-security-policy: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'"
      x-content-type-options: nosniff
      x-frame-options: DENY
      x-xss-protection: "1; mode=block"
      strict-transport-security: "max-age=31536000; includeSubDomains"
      
  # Feature Flags
  features:
    auth-microservice: ${FEATURE_AUTH_MS}
    jwks-rotation: ${FEATURE_JWKS_ROTATION}
    audit-logging: ${FEATURE_AUDIT_LOGGING}
    metrics-collection: ${FEATURE_METRICS}

# Logging Configuration
logging:
  level:
    "[br.tec.facilitaservicos.autenticacao]": ${LOG_LEVEL}
    "[org.springframework.security]": ${SECURITY_LOG_LEVEL}
    "[org.springframework.r2dbc]": ${R2DBC_LOG_LEVEL}
    "[io.r2dbc.mysql]": ${MYSQL_LOG_LEVEL}
    "[com.azure]": ${AZURE_LOG_LEVEL}
    
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    
  file:
    name: ${LOG_FILE}

# OpenAPI Documentation
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false
  
# Resilience4j Configuration
resilience4j:
  ratelimiter:
    instances:
      auth-service:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 3s
        
  circuitbreaker:
    instances:
      azure-keyvault:
        sliding-window-size: 100
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 5

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
      
  # Habilitar Key Vault em produção
  cloud:
    azure:
      keyvault:
        secret:
          enabled: ${AZURE_KEYVAULT_ENABLED}
          
# Configurações específicas de produção (sobrescrevendo padrões)
server:
  ssl:
    enabled: false  # TLS termina no Traefik (ACME) - forçar false
      
app:
  jwt:
    key-vault:
      enabled: ${JWT_KEYVAULT_ENABLED}
  features:
    auth-microservice: true
    jwks-rotation: true
    audit-logging: true
    metrics-collection: true
  rate-limit:
    default-requests-per-minute: 30
    endpoints:
      "/auth/token":
        requests-per-minute: 5
      "/auth/refresh":
        requests-per-minute: 15
      
logging:
  level:
    "[br.tec.facilitaservicos.autenticacao]": INFO
    root: WARN
    "[org.springframework.security]": WARN
    "[org.springframework.r2dbc]": WARN
    "[io.r2dbc.mysql]": WARN
    "[com.azure]": WARN
    
  file:
    name: /var/log/autenticacao/application.log
